<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ADS61" name="Test" tests="5" failures="3" timestamp="10 Oct 2017 11:42:47 GMT" time="0.469" errors="0">
  <testcase name="ArthaDB_Customer_FirstName_Check_TC001" time="0.014" classname="exe.Arthadb_Automation">
    <failure type="junit.framework.AssertionFailedError" message="CUSTOMERS FirstName check is Failed at SSN=123-45-6781,123-45-6782, expected:&amp;lt;0&amp;gt; but was:&amp;lt;2&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: CUSTOMERS FirstName check is Failed at SSN=123-45-6781,123-45-6782, expected:<0> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.Arthadb_Automation.ArthaDB_Customer_FirstName_Check_TC001(Arthadb_Automation.java:97)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- ArthaDB_Customer_FirstName_Check_TC001 -->
  <testcase name="ArthaDB_Customers_SSN_Check_TC002" time="0.006" classname="exe.Arthadb_Automation"/>
  <testcase name="ArthaDB_PrimaryPhoneNumber_TC003" time="0.005" classname="exe.Arthadb_Automation">
    <failure type="junit.framework.AssertionFailedError" message="Customer PrimaryPhoneNumber check is Failed at SSN=123-45-6781, expected:&amp;lt;0&amp;gt; but was:&amp;lt;1&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: Customer PrimaryPhoneNumber check is Failed at SSN=123-45-6781, expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.Arthadb_Automation.ArthaDB_PrimaryPhoneNumber_TC003(Arthadb_Automation.java:182)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- ArthaDB_PrimaryPhoneNumber_TC003 -->
  <testcase name="ArthaDB_Customer_LastName_Check_TC004" time="0.002" classname="exe.Arthadb_Automation"/>
  <testcase name="ArthaDB_Customer_MailingAddressZipCode_Check_TC005" time="0.003" classname="exe.Arthadb_Automation">
    <failure type="junit.framework.AssertionFailedError" message="CUSTOMERS MailingAddressZipCode check is Failed at SSN=123-45-6784,123-45-6785, expected:&amp;lt;0&amp;gt; but was:&amp;lt;2&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: CUSTOMERS MailingAddressZipCode check is Failed at SSN=123-45-6784,123-45-6785, expected:<0> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.Arthadb_Automation.ArthaDB_Customer_MailingAddressZipCode_Check_TC005(Arthadb_Automation.java:221)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- ArthaDB_Customer_MailingAddressZipCode_Check_TC005 -->
</testsuite> <!-- Test -->
